WITH existing_master_ids AS (
    SELECT RAP_METRICS_MAPPING_ID,
           MAX(MASTER_METRIC_ID) AS MASTER_METRIC_ID
    FROM RAP_METRICS_DETAILS
    WHERE MASTER_METRIC_ID IS NOT NULL
    GROUP BY RAP_METRICS_MAPPING_ID
)
SELECT d.METRIC_DETAIL_ID,
       d.RAP_ID,
       d.RAP_METRICS_MAPPING_ID,
       d.METRICS_DISPLAY,
       d.MASTER_METRIC_ID AS current_master_metric_id,
       mm.MASTER_METRIC_ID AS mapped_master_metric_id
FROM RAP_METRICS_DETAILS d
JOIN RAP r
  ON d.RAP_ID = r.RAP_ID
JOIN MEET_INSTC mi
  ON r.RAP_INSTANCE_ID = mi.MEET_INSTC_ID
JOIN RAP_METRICS_PACK_MAPPING p
  ON d.RAP_METRICS_MAPPING_ID = p.RAP_METRICS_MAPPING_ID
LEFT JOIN existing_master_ids mm
  ON d.RAP_METRICS_MAPPING_ID = mm.RAP_METRICS_MAPPING_ID
WHERE d.MASTER_METRIC_ID IS NULL
  AND mi.ACT_ON_RCRD = 'insert-rap-open'
  AND mi.MEET_INSTC_ID = 11657
ORDER BY d.RAP_METRICS_MAPPING_ID, d.METRIC_DETAIL_ID;
