SELECT DISTINCT d.MASTER_METRIC_ID
FROM RAP_METRICS_DETAILS d
WHERE NOT EXISTS (
    SELECT 1
    FROM RAP_MASTER_METRIC_DETAILS m
    WHERE m.MASTER_METRIC_ID = d.MASTER_METRIC_ID
);


SELECT DISTINCT d.MASTER_METRIC_ID,
       d.RAP_RISK_TYPE_ID,
       p.METRICS_DISPLAY AS EXPECTED_NAME
FROM RAP_METRICS_DETAILS d
JOIN RAP_METRICS_PACK_MAPPING p
  ON d.RAP_METRICS_MAPPING_ID = p.RAP_METRICS_MAPPING_ID
WHERE NOT EXISTS (
    SELECT 1
    FROM RAP_MASTER_METRIC_DETAILS m
    WHERE m.MASTER_METRIC_ID = d.MASTER_METRIC_ID
);


=================

SELECT m.MASTER_METRIC_ID,
       m.MASTER_METRIC_NAME AS OLD_MASTER_NAME,
       p.METRICS_DISPLAY    AS NEW_MASTER_NAME,
       m.MASTER_METRIC_RISK_TYPE_ID,
       d.RAP_METRICS_MAPPING_ID
FROM RAP_MASTER_METRIC_DETAILS m
JOIN RAP_METRICS_DETAILS d
  ON d.MASTER_METRIC_ID = m.MASTER_METRIC_ID
JOIN RAP_METRICS_PACK_MAPPING p
  ON d.RAP_METRICS_MAPPING_ID = p.RAP_METRICS_MAPPING_ID
WHERE d.RAP_RISK_TYPE_ID = m.MASTER_METRIC_RISK_TYPE_ID
  AND m.MASTER_METRIC_NAME <> p.METRICS_DISPLAY;


UPDATE RAP_MASTER_METRIC_DETAILS m
SET m.MASTER_METRIC_NAME = (
        SELECT p.METRICS_DISPLAY
        FROM RAP_METRICS_DETAILS d
        JOIN RAP_METRICS_PACK_MAPPING p 
             ON d.RAP_METRICS_MAPPING_ID = p.RAP_METRICS_MAPPING_ID
        WHERE d.MASTER_METRIC_ID = m.MASTER_METRIC_ID
          AND d.RAP_RISK_TYPE_ID = m.MASTER_METRIC_RISK_TYPE_ID
          AND m.MASTER_METRIC_NAME <> p.METRICS_DISPLAY
          FETCH FIRST 1 ROWS ONLY
)
WHERE EXISTS (
    SELECT 1
    FROM RAP_METRICS_DETAILS d
    JOIN RAP_METRICS_PACK_MAPPING p 
         ON d.RAP_METRICS_MAPPING_ID = p.RAP_METRICS_MAPPING_ID
    WHERE d.MASTER_METRIC_ID = m.MASTER_METRIC_ID
      AND d.RAP_RISK_TYPE_ID = m.MASTER_METRIC_RISK_TYPE_ID
      AND m.MASTER_METRIC_NAME <> p.METRICS_DISPLAY
)
RETURNING m.MASTER_METRIC_ID, :OLD_NAME, m.MASTER_METRIC_NAME INTO :id_var, :old_name_var, :new_name_var;


INSERT INTO MASTER_METRIC_UPDATE_LOG (MASTER_METRIC_ID, OLD_NAME, NEW_NAME, RISK_TYPE_ID, UPDATE_DATE)
SELECT m.MASTER_METRIC_ID,
       m.MASTER_METRIC_NAME,
       p.METRICS_DISPLAY,
       m.MASTER_METRIC_RISK_TYPE_ID,
       SYSDATE
FROM RAP_MASTER_METRIC_DETAILS m
JOIN RAP_METRICS_DETAILS d
  ON d.MASTER_METRIC_ID = m.MASTER_METRIC_ID
JOIN RAP_METRICS_PACK_MAPPING p
  ON d.RAP_METRICS_MAPPING_ID = p.RAP_METRICS_MAPPING_ID
WHERE d.RAP_RISK_TYPE_ID = m.MASTER_METRIC_RISK_TYPE_ID
  AND m.MASTER_METRIC_NAME <> p.METRICS_DISPLAY;
